# executable files for this directory
OBJECTS = maptest.exe settest.exe exec11_3.exe multi.exe exec11_7.exe exec11_8.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
