# executable files for this directory
OBJECTS = container.exe exec9_4.exe exec9_10.exe exec9_11.exe exec9_13.exe exec9_14.exe compare.exe exec9_16.exe addelement.cpp

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
