# executable files for this directory
OBJECTS = container.exe exec9_4.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
