# executable files for this directory
OBJECTS = container.exe exec9_4.exe exec9_10.exe exec9_11.exe exec9_13.exe exec9_14.exe compare.exe exec9_16.exe addelement.exe exec9_18.exe emplace.exe insert.exe exec9_20.exe exec9_22.exe vistor.exe exec9_23.exe exec9_24.exe delelement.exe exec9_25.exe exec9_26.exe size_cap.exe stack.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
