# executable files for this directory
OBJECTS = trycatch.exe exec5_23.exe exec5_25.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
