# executable files for this directory
OBJECTS = test.exe exec4_4.exe exec4_10.exe


# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
