# executable files for this directory
OBJECTS = string.exe vector.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
