# executable files for this directory
OBJECTS = abs_class.exe exec7_4.exe class_construct.exe exec7_11.exe class_access.exe exec7_19.exe class_friend.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
