# executable files for this directory
OBJECTS = exec15_3.exe derivation.exe static_deriv.exe exec15_5.exe exec15_6.exe exec15_7.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
