# executable files for this directory
OBJECTS = find.exe exec10_1.exe exec10_3.exe exec10_4.exe exec10_5.exe fill.exe backinsert.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
