# executable files for this directory
OBJECTS = io_class.exe exec8_1.exe exec8_3.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
