# executable files for this directory
OBJECTS = func.exe exec6_4.exe exec6_5.exe exec6_11.exe exec6_12.exe exec6_15.exe exec6_17.exe arrayparam.exe exec6_22.exe exec6_25.exe exec6_32.exe exec6_36.exe exec6_38.exe exec6_40.exe exec6_50.exe exec6_54.exe exec6_55.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
