# executable files for this directory
OBJECTS = func.exe exec6_4.exe exec6_5.exe exec6_11.exe exec6_12.exe exec6_15.exe exec6_17.exe arrayparam.exe

# tells make to use the file "../GNU_makefile_template", which
# defines general rules for making .o and .exe files
include ../GNU_makefile_template
